# Generated by Django 5.0.3 on 2024-03-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_devicelog_checked_in_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='checked_in_date',
        ),
    ]
